[toolchain]
channel = "1.88.0" # rustc 1.88.0 (6b00bc388 2025-06-23)
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-src",
	"rust-std",
	"rustc-dev",
	"rustc",
	"rustfmt",
]
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"
